#! /usr/bin/env php
<?php

use crazyfactory\generator\Crazy;
use Symfony\Component\Console\Application;

require_once 'vendor/autoload.php';

$app = new Application(Crazy::NAME, Crazy::VERSION);

$app->add(new \crazyfactory\generator\Create());

$app->run();
